name: auto-merge

on:
  pull_request:

jobs:
  test:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-18.04
    steps:
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-minor: true
          merge-patch: true
